### ISSUE TITLE
Documentation version 1.0 says compatible with 3.5

### ISSUE THREAD

**Issue by 99sono** [rdebusscher/AdvancedGraphicImageRenderer#3]
Hi,

The documentation for the releases says that version 1.0 is meant to work with releases 3.5.x , but the version it was built against apparently was:
<primefaces.version>3.4.1</primefaces.version>

I've just tried deploying against 3.5 and the code and it broke with:

<code>
va.lang.NoSuchMethodError: be.rubus.web.jsf.primefaces.AdvancedGraphicImageRenderer.createUniqueContentId(Ljavax/faces/context/FacesContext;)Ljava/lang/String;
    at be.rubus.web.jsf.primefaces.AdvancedGraphicImageRenderer.getImageSrc(AdvancedGraphicImageRenderer.java:79)
    at org.primefaces.component.graphicimage.GraphicImageRenderer.encodeEnd(GraphicImageRenderer.java:41)
    at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:881)
    at com.sun.faces.renderkit.html_basic.HtmlBasicRenderer.encodeRecursive(HtmlBasicRenderer.java:312)
    at com.sun.faces.renderkit.html_basic.GroupRenderer.encodeChildren(GroupRenderer.java:105)

</code>

Regards.

**Comment by rdebusscher** [comment]
createUniqueContentId is present in PF 3.4.1 AND 3.5.

I don't have any problems in compiling it against 3.5

I see that the method is removed on 23/5/2013, in preparation of the 4.0 release.
